mineral_catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('minerals.urls', namespace='minerals')),
]

# checks for debug mode
# if so, adds a static path that points to the files in the static folders
urlpatterns += staticfiles_urlpatterns()

minerals/urls.py
from django.urls import path
from . import views

app_name = 'minerals'

urlpatterns = [
    path('', views.mineral_list, name='list'),
    path('minerals/', views.mineral_list, name='filtered_list'),
    path('mineral/<int:mineral_id>/', views.mineral_detail, name="detail"),
    path('search/', views.search, name='search')
]

minerals/models.py
from django.db import models

# Create your models here.


class Mineral(models.Model):
    """
        Not all entries will have every field as shown in the json file in "mineral_data/mineral.json"
    """
    name = models.CharField(max_length=255, blank=True, default='')
    image_filename = models.CharField(max_length=255, blank=True, default='')
    image_caption = models.TextField(blank=True, default='')
    category = models.CharField(max_length=255, blank=True, default='')
    formula = models.CharField(max_length=255, blank=True, default='')
    strunz_classification = models.CharField(max_length=255, blank=True, default='')
    color = models.CharField(max_length=255, blank=True, default='')
    crystal_system = models.CharField(max_length=255, blank=True, default='')
    unit_cell = models.CharField(max_length=255, blank=True, default='')
    crystal_symmetry = models.CharField(max_length=255, blank=True, default='')
    cleavage = models.CharField(max_length=255, blank=True, default='')
    mohs_scale_hardness = models.CharField(max_length=255, blank=True, default='')
    luster = models.CharField(max_length=255, blank=True, default='')
    streak = models.CharField(max_length=255, blank=True, default='')
    diaphaneity = models.CharField(max_length=255, blank=True, default='')
    optical_properties = models.CharField(max_length=255, blank=True, default='')
    refractive_index = models.CharField(max_length=255, blank=True, default='')
    crystal_habit = models.CharField(max_length=255, blank=True, default='')
    specific_gravity = models.CharField(max_length=255, blank=True, default='')
    group = models.CharField(max_length=255, blank=True, default='')

minerals/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .models import Mineral

# Create your views here.

def mineral_list(request):
    starts_with = request.GET.get('starts_with', None)
    group = request.GET.get('group', None)
    if group:
        minerals = Mineral.objects.filter(
          Q(group__iexact=group)
        )
    elif starts_with:
        minerals = Mineral.objects.filter(
          Q(name__istartswith=starts_with)
        )
    else:
        minerals = Mineral.objects.filter(
          Q(name__istartswith='A')
        )
    context = {
      'minerals': minerals,
      'letter': starts_with,
      'group': group
    }
    return render(request, 'minerals/mineral_list.html', context=context)


def mineral_detail(request, mineral_id):
    mineral = get_object_or_404(Mineral, pk=mineral_id)
    return render(request, 'minerals/mineral_detail.html', {'mineral': mineral})


def search(request):
    term = request.GET.get('query')
    minerals = Mineral.objects.filter(
      Q(name__icontains=term)|Q(mohs_scale_hardness__exact=term)|Q(crystal_system__icontains=term)
    )
    return render(request, 'minerals/mineral_list.html', {'minerals': minerals})

minerals/templates/minerals/group_menu.html
<section>
    <h3>Group</h3>
    <ul class='filter-submenu group-menu'>
      {% for group in groups %}
      <li>
        <a
        class="{% if active_group == group %}active_link{% endif %}"
        href="{% url 'minerals:filtered_list' %}?group={{ group }}">{{ group }}</a>
      </li>
    {% endfor %}
    </ul>
</section>

minerals/templates/minerals/letter_menu.html
<section>
  <h4>{{ request.get_full_path }}</h4>
    <h3>Starts With</h3>
    <ul class='filter-submenu letter-menu'>
        {% for letter in letters %}
          <li>
            <a 
                class="{% if active_letter == letter %}active_link{% endif %}" 
                href="{% url 'minerals:filtered_list' %}?starts_with={{ letter }}">
                {{ letter }}
            </a>
          </li>
        {% endfor %}
    </ul>
</section>

minerals/templates/minerals/mineral_detail.html
{% extends "layout.html" %}

{% load static %}
{% load mineral_extras %}

{% block content %}

    <section class="filter-menu">
      <h2>Filter</h2>
      {% group_menu active_group='' %}
      {% letter_menu active_letter='' %}
    </section>

    <div class="grid-100 mineral__container">
      <h1 class="mineral__name">{{ mineral.name }}</h1>
      <div class="mineral__image-bg">
          <img class="mineral__image" alt="{{ mineral.name }}" src="{% get_static_prefix %}images/{{mineral.name}}.jpg">
        <p class="mineral__caption">{{ mineral.image_caption }}</p>
      </div>
      <div class="mineral__table-container">
        <table class="mineral__table">
          <tr>
            <td class="mineral__category">Category</td>
            <td>{{ mineral.category|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Group</td>
            <td>{{ mineral.group|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Formula</td>
            <td class="mineral__formula">{{ mineral.formula|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Strunz Classification</td>
            <td>{{ mineral.strunz_classification|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Unit Cell</td>
            <td>{{ mineral.unit_cell|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Color</td>
            <td>{{ mineral.color|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Crystal Habit</td>
            <td>{{ mineral.crystal_habit|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Crystal System</td>
            <td>{{ mineral.crystal_system|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Crystal Symmetry</td>
            <td>{{ mineral.crystal_symmetry|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Mohs Scale Hardness</td>
            <td>{{ mineral.mohs_scale_hardness|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Cleavage</td>
            <td>{{ mineral.cleavage|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Luster</td>
            <td>{{ mineral.luster|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Streak</td>
            <td>{{ mineral.streak|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Diaphaneity</td>
            <td>{{ mineral.diaphaneity|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Optical Properties</td>
            <td>{{ mineral.optical_properties|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Refractive Index</td>
            <td>{{ mineral.refractive_index|field_or_na }}</td>
          </tr>
          <tr>
            <td class="mineral__category">Specific Gravity</td>
            <td>{{ mineral.specific_gravity|field_or_na }}</td>
          </tr>
        </table>
      </div>
    </div>
{% endblock %}

minerals/templates/minerals/mineral_list.html
{% extends "layout.html" %}
{% load mineral_extras %}

{% block content %}

    <section class="filter-menu">
        <h2>Filter</h2>
        {% group_menu active_group=group %}
        {% letter_menu active_letter=letter %}
    </section>

    <div class="grid-100">
        {% if minerals.count == 0 %}
            <h2>Sorry, no results were found.</h2>
        {% else %}
            <ul class="minerals__container">
                {% for mineral in minerals %}
                    <li class="minerals__item">
                        <a class="minerals__anchor" href="{% url 'minerals:detail' mineral.id %}">{{ mineral.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
{% load mineral_extras %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Macky's Minerals: A magnificant catalog of minerals</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>

      <nav>
          <div>
              <a href="{% url 'minerals:list' %}">
                <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
                  <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
                  <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
                  <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
                </svg>
                <h1 class="logo__name text-centered">Macky's Minerals</h1>
              </a>
              <p class="logo__text text-centered">They're not rocks!</p>
          </div>
          
          <!-- Search Feature -->
          <form action="{% url 'minerals:search' %}" method='get' class='search'>
            <input type="search" name="query" id="query" placeholder="Name, Mohs Scale Hardness, Crystal System">
            <input class="minerals__anchor form-btn" type="submit" value="Search">
          </form>
      </nav>
    
  <div class="bounds">

      {% block content %}
      {% endblock %}

  </div>

  <div class="minerals__random">
    {% random_mineral_id as id %}
      <a class="minerals__anchor" href="{% url 'minerals:detail' id %}">Show random mineral</a>
  </div>
</body>
</html>